### PR TITLE
Add static code analyzer

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
The `lp` part might be replaced by direct socket connections to the printers:
```
$fp=pfsockopen(PRINTER_IP_ADDRESS, 9100);
fputs($fp, $print_data);
fclose($fp);
```

I am not sure whether that works with all our printers and whether it's worth the trouble.

**Comment by jmechnich** [comment]
Nope, we are using and want to use the local CUPS server.

**Comment by jmechnich** [comment]
In any case, if the code still works I am going to merge this. As a later TODO, we can think of additional measures for protecting the input to the processing, e.g. restrictions on the email header etc.

**Comment by stweil** [comment]
Unrelated question: Did we ever try [mpdf](https://github.com/mpdf/mpdf) as a replacement for weasyprint?

**Pull request merged**
